### ISSUE TITLE
Missing papers

### ISSUE THREAD

**Issue by dxlong2000** [Neph0s/awesome-llm-role-playing-with-persona#13]
Dear authors,

Thank you for the great list. I would like to invite adding two papers:

- [Multi-expert Prompting Improves Reliability, Safety, and Usefulness of Large Language Models](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=uZyF8wwAAAAJ&sortby=pubdate&citation_for_view=uZyF8wwAAAAJ:iH-uZ7U-co4C), EMNLP 2024
- [Aligning Large Language Models with Human Opinions through Persona Selection and Value–Belief–Norm Reasoning](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=uZyF8wwAAAAJ&sortby=pubdate&citation_for_view=uZyF8wwAAAAJ:Se3iqnhoufwC)

Thanks!

**Comment by Neph0s** [comment]
Hey, thanks for sharing! You are encouraged to open a pull-request to add the papers. 

This repo now focuses primarily on the **representing specific personas** side of role-playing. According to the current taxonomy, i think these papers might better fit in the 'Anthropomorphic Cognition/Other' or 'Other/Paper' sections.

**Comment by dxlong2000** [comment]
Hello @Neph0s, thanks for your recommendations. I believe Multi-expert Prompting is suitable for the Multi agent category since it is a multi-expert system; and Chain of opinion is reasoning over demographics, so I added in demographic section. I think Anthropomorphic is more like anthropomorphic not only reasoning ;))

Thanks!
